name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build -t flask-app . 
      
    - name: Tage the Docker image  
      run: docker tag flask-app:latest ahmedsamymahrous/flask-app:latest
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Push the Docker image to Dockerhub
      run: docker push ahmedsamymahrous/flask-app:latest

    # - name: Deploy Stack
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: 3.136.233.198
    #     username: ubuntu
    #     key: ${{ secrets.MASTER_SSH_PRIVATE_KEY }}
    #     script: docker stack deploy -c docker-compose.yml flask-app


    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: 👨🏻‍💻 User ${{github.actor}} in ${{ github.repository }} repository. Make ${{ github.event_name }}. Job ${{github.job}} = ${{ job.status }}
